# Bài thực hành 5

In [12]:
#import dữ liệu
import pandas as pd
import numpy as np

## 1. Đọc dữ liệu

In [88]:
df = pd.read_excel("Data_PhanLopDL.xlsx")
df.head()

Make Colour  Odometer (KM)  Doors Class
0   Honda  White        35431.0    4.0     B
1     BMW    NaN       192714.0    5.0     B
2   Honda  White            NaN    4.0     C
3     NaN  White       154365.0    4.0     B
4  Nissan   Blue       181577.0    3.0     B

## 2. Xem các thông tin về dữ liệu

In [3]:
#xem thông tin về kích thước dữ liệu
df.dtypes

Make              object
Colour            object
Odometer (KM)    float64
Doors            float64
Class             object
dtype: object

In [4]:
#xem thông tin vê thuộc tính
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Make           994 non-null    object 
 1   Colour         994 non-null    object 
 2   Odometer (KM)  993 non-null    float64
 3   Doors          995 non-null    float64
 4   Class          1000 non-null   object 
dtypes: float64(2), object(3)
memory usage: 39.2+ KB


In [66]:
#Kiểm tra xem dữ liệu có thiếu hay không
df.isnull().sum()

Make             33
Colour           25
Odometer (KM)    32
Doors             5
Class             0
dtype: int64

In [30]:
# Nhìn vào kết quả có thể thấy chỉ cột class là không thiếu dữ liệu
#Xác định X, y
# Cho X bằng cột 'Make', 'Colour', 'Odometer', 'Doors'
# Cho y bằng cột 'Class'

In [45]:
# Xác định số lớp của y
y = df.Class

print("Unique: ",y.unique(), "\nUnique: ", y.nunique(),"\nValue count:\n", y.value_counts())

Unique:  ['B' 'C' 'A' 'D'] 
Unique:  4 
Value count:
 Class
B    451
A    275
C    199
D     75
Name: count, dtype: int64


## 3. Xử lý dữ liệu

In [5]:
#Kiểm tra xem dữ liệu có bị thiếu không
#lấy ra tất cả thông tin của hãng xe
df.Make.unique()

array(['Honda', 'BMW', 'Toyota', 'Nissan', nan], dtype=object)

In [89]:
#Thay thế các dữ liệu trống bằng Porsche
df.Make = df.Make.replace(np.nan, 'Porsche')
df

Make Colour  Odometer (KM)  Doors Class
0      Honda  White        35431.0    4.0     B
1        BMW    NaN       192714.0    5.0     B
2      Honda  White            NaN    4.0     C
3    Porsche  White       154365.0    4.0     B
4     Nissan   Blue       181577.0    3.0     B
..       ...    ...            ...    ...   ...
995   Toyota  Black        35820.0    4.0     D
996   Nissan  White       155144.0    3.0     A
997   Nissan   Blue        66604.0    4.0     D
998    Honda  White       215883.0    4.0     A
999   Toyota   Blue       248360.0    4.0     B

[1000 rows x 5 columns]

In [73]:
#Kiểm tra cột colour
df.Make.unique()

array(['Honda', 'BMW', 'Porsche', 'Nissan', 'Toyota'], dtype=object)

In [21]:
df['Make'].value_counts()

Make
Toyota     386
Honda      292
Nissan     192
BMW         97
Porsche     33
Name: count, dtype: int64

In [74]:
#Xử lý dữ liệu cột màu
df.Colour.unique()

array(['White', nan, 'Blue', 'Red', 'Green', 'Black'], dtype=object)

In [72]:
df.Colour.value_counts()

Colour
White    395
Blue     312
Black     99
Red       91
Green     78
Name: count, dtype: int64

In [90]:
#Lấy giá trị màu xuất hiện nhiều nhất và gán cho những màu bị thiếu
max_color = df['Colour'].value_counts().idxmax()
df.Colour = df.Colour.replace(np.nan, max_color)
df.Colour.unique()

array(['White', 'Blue', 'Red', 'Green', 'Black'], dtype=object)

In [63]:
#Kiểm tra cột Odometer (KM)
df['Odometer (KM)'].unique()

array([ 35431., 192714., 154365., 181577.,  42652., 163453.,  43120.,
       130538.,  51029., 167421.,  17119., 102303., 199833., 205592.,
        96742., 194189.,  67991., 215820., 124844.,  30615., 148744.,
       130075., 172718., 125819., 180390.,  82783., 112004.,  34024.,
       108569., 203795., 153554.,  71949.,  38186.,  69888., 146430.,
       109868., 177894., 189209., 200490., 141617., 213893., 231057.,
       100938., 243969., 107096., 184878., 161068.,  77646., 246817.,
       109384.,  79937.,  82039., 162176.,  97375., 230908., 208124.,
        57198.,  47019., 170085., 178796., 223390.,  93054.,  42459.,
        37513., 123121., 204213., 116986., 191232., 156478., 140465.,
       126669., 238425., 186146., 149879.,  34097., 248447.,  61651.,
        24219., 209359., 108415.,  61892.,  90249., 197844.,  53765.,
       115183., 130783., 143707.,  29856., 133433., 147455.,  48069.,
       146233., 224657., 150582.,  71329., 229206., 218803., 184869.,
       129769., 2192

In [91]:
#Xóa các dòng thiếu dữ liệu
df = df.dropna(subset=['Odometer (KM)'])
df.head()

Make Colour  Odometer (KM)  Doors Class
0    Honda  White        35431.0    4.0     B
1      BMW  White       192714.0    5.0     B
3  Porsche  White       154365.0    4.0     B
4   Nissan   Blue       181577.0    3.0     B
5    Honda    Red        42652.0    4.0     C

In [92]:
#Kiêm tra cột door
df.Doors.unique()

array([ 4.,  5.,  3., nan])

In [93]:
#thay thế thành 2 cửa
df.Doors = df.Doors.replace(np.nan, 2)
df.Doors.unique()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13208\2348146177.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Doors = df.Doors.replace(np.nan, 2)


array([4., 5., 3., 2.])

In [60]:
# Báo lỗi nhưng vẫn hiện kết quả?
#tách X
X = df.iloc[:, :-1]
X

Make Colour  Odometer (KM)  Doors
0     Honda  White        35431.0    4.0
1       BMW  White       192714.0    5.0
3       NaN  White       154365.0    4.0
4    Nissan   Blue       181577.0    3.0
5     Honda    Red        42652.0    4.0
..      ...    ...            ...    ...
995  Toyota  Black        35820.0    4.0
996  Nissan  White       155144.0    3.0
997  Nissan   Blue        66604.0    4.0
998   Honda  White       215883.0    4.0
999  Toyota   Blue       248360.0    4.0

[968 rows x 4 columns]

In [61]:
#tách y
y = df.iloc[:, -1]
y

0      B
1      B
3      B
4      B
5      C
      ..
995    D
996    A
997    D
998    A
999    B
Name: Class, Length: 968, dtype: object

In [95]:
#Xử lý dữ liệu cho X
#Chuyển kiểu cho 2 thuộc tính Make và Colour: định danh -> số
X = pd.get_dummies(X, dtype = int, columns = ['Make', 'Colour'])
X.head(10)

Odometer (KM)  Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  \
0         35431.0    4.0         0           1            0            0   
1        192714.0    5.0         1           0            0            0   
3        154365.0    4.0         0           0            0            0   
4        181577.0    3.0         0           0            1            0   
5         42652.0    4.0         0           1            0            0   
6        163453.0    4.0         0           0            0            1   
7         43120.0    4.0         0           1            0            0   
8        130538.0    4.0         0           0            1            0   
9         51029.0    4.0         0           1            0            0   
10       167421.0    4.0         0           0            1            0   

    Colour_Black  Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0            0             0           0             1  
1              0            0             0           0             1  
3              0            0             0           0             1  
4              0            1             0           0             0  
5              0            0             0           1             0  
6              0            1             0           0             0  
7              0            0             0           0             1  
8              0            0             0           0             1  
9              0            1             0           0             0  
10             0            0             0           0             1

In [96]:
# Chuẩn hóa thuộc tính Odometer (KM) về miền [1,5]
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))
X["Odometer (KM)"] = scaler.fit_transform(X[["Odometer (KM)"]])
X

Odometer (KM)  Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  \
0         0.105472    4.0         0           1            0            0   
1         0.761606    5.0         1           0            0            0   
3         0.601626    4.0         0           0            0            0   
4         0.715146    3.0         0           0            1            0   
5         0.135596    4.0         0           1            0            0   
..             ...    ...       ...         ...          ...          ...   
995       0.107095    4.0         0           0            0            1   
996       0.604876    3.0         0           0            1            0   
997       0.235516    4.0         0           0            1            0   
998       0.858259    4.0         0           1            0            0   
999       0.993742    4.0         0           0            0            1   

     Colour_Black  Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0               0            0             0           0             1  
1               0            0             0           0             1  
3               0            0             0           0             1  
4               0            1             0           0             0  
5               0            0             0           1             0  
..            ...          ...           ...         ...           ...  
995             1            0             0           0             0  
996             0            0             0           0             1  
997             0            1             0           0             0  
998             0            0             0           0             1  
999             0            1             0           0             0  

[968 rows x 11 columns]

## Phân lớp dữ liệu